name: Build INJOLOCA Extension

on:
  push:
    branches:
      - master
      
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Tipo de incremento de versão'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release   # apenas aprovadores do environment podem executar
    if: github.ref == 'refs/heads/master'  # somente master

    steps:
      # 1️⃣ Checkout completo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Setup Node.js para semver
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install semver
        run: npm install semver

      # 3️⃣ Bump version seguro
      - name: Bump version
        id: bump
        run: node bump_version.js
        env:
          BUMP_TYPE: ${{ github.event.inputs.bump_type }}

      # 4️⃣ Commit + tag
      - name: Commit new version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add manifest.json
          git commit -m "Bump version to ${{ steps.bump.outputs.new_version }}"
          git tag v${{ steps.bump.outputs.new_version }}
          git push origin HEAD:master --tags

      # 5️⃣ Criar ZIP da extensão com arquivos essenciais
      - name: Create ZIP for Chrome Web Store
        run: |
          ZIP_NAME="injoloca-${{ steps.bump.outputs.new_version }}.zip"
          zip -r $ZIP_NAME \
            manifest.json \
            popup.html \
            popup.js \
            LICENCE \
            background.js \
            icon48.png \
            icon128.png
          echo "Extension ZIP created: $ZIP_NAME"

      # 6️⃣ Upload ZIP como artifact
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: injoloca-extension
          path: injoloca-${{ steps.bump.outputs.new_version }}.zip
